export const wildPromptData = [
  { topic: "The dirtiest sexual encounter I had was…", prompts: ["In a forbidden place", "With an unexpected person", "Driven by a kink", "Completely spontaneous"], mode: "wild" },
  { topic: "A fantasy I’ve never shared involves…", prompts: ["A taboo roleplay", "Multiple partners", "A public act", "A psychological kink"], mode: "wild" },
  { topic: "I was most aroused when…", prompts: ["Caught in the act", "Exploring a fetish", "Receiving a naughty text", "Hearing a sexual confession"], mode: "wild" },
  { topic: "The kinkiest act I’ve done was…", prompts: ["Bondage with ropes", "Domination/submission", "Exhibitionism", "A secret fetish"], mode: "wild" },
  { topic: "I masturbated thinking about…", prompts: ["A past lover’s touch", "A stranger’s gaze", "A forbidden scenario", "A vivid porn scene"], mode: "wild" },
  { topic: "The riskiest place I had sex was…", prompts: ["A public restroom", "A moving vehicle", "A quiet park", "Someone else’s bed"], mode: "wild" },
  { topic: "A sex toy that changed my experience was…", prompts: ["A vibrator’s intensity", "A restraint", "An anal toy", "Something experimental"], mode: "wild" },
  { topic: "My most memorable oral moment was…", prompts: ["Giving in a rush", "Receiving unexpectedly", "In a daring location", "With a kinky twist"], mode: "wild" },
  { topic: "A threesome I experienced or imagined was…", prompts: ["With strangers", "With friends", "A fantasy I crave", "A regretful moment"], mode: "wild" },
  { topic: "I got caught during…", prompts: ["A hookup", "Masturbation", "Sexting someone", "A naughty act"], mode: "wild" },
  { topic: "The wildest sexual position I tried was…", prompts: ["Physically challenging", "Deeply intimate", "Publicly risky", "Kink-driven"], mode: "wild" },
  { topic: "A porn that got me going was…", prompts: ["A specific fetish", "Amateur and raw", "Watched with a partner", "Totally unexpected"], mode: "wild" },
  { topic: "The hottest sext I sent or received was…", prompts: ["Explicitly detailed", "With a nude", "To the wrong person", "Igniting a hookup"], mode: "wild" },
  { topic: "My most intense orgasm came from…", prompts: ["A new kink", "A risky setting", "Emotional connection", "Pure physicality"], mode: "wild" },
  { topic: "A fetish that drives me wild is…", prompts: ["Power dynamics", "Sensory play", "Voyeurism", "Something taboo"], mode: "wild" },
  { topic: "I hooked up with someone…", prompts: ["I shouldn’t have", "At a wild party", "Much older/younger", "Completely random"], mode: "wild" },
  { topic: "The naughtiest roleplay I’ve done was…", prompts: ["Authority figure", "Strangers meeting", "Taboo scenario", "Fantasy-driven"], mode: "wild" },
  { topic: "I used an unusual item for…", prompts: ["Pleasure", "A kink", "Foreplay", "A dare"], mode: "wild" },
  { topic: "The most psychologically intense sex was…", prompts: ["Driven by desire", "Emotionally charged", "A power exchange", "A secret"], mode: "wild" },
  { topic: "I tried bondage and felt…", prompts: ["Liberated", "Vulnerable", "Thrilled", "Overwhelmed"], mode: "wild" },
  { topic: "The dirtiest thing I’ve said in bed was…", prompts: ["Purely instinctive", "Shockingly bold", "A fantasy reveal", "Embarrassing"], mode: "wild" },
  { topic: "I had sex somewhere…", prompts: ["Totally exposed", "Luxurious", "Unhygienic", "Emotionally charged"], mode: "wild" },
  { topic: "A stranger I was drawn to sexually was…", prompts: ["Mysterious", "Boldly flirty", "Physically striking", "A fleeting encounter"], mode: "wild" },
  { topic: "I got frisky during…", prompts: ["A public event", "A quiet moment", "A friend’s gathering", "An odd setting"], mode: "wild" },
  { topic: "A sex game that turned me on was…", prompts: ["Truth or dare", "Strip challenge", "Roleplay bet", "Kinky rules"], mode: "wild" },
  { topic: "I explored a kink like…", prompts: ["Public exposure", "Submission", "Sensory deprivation", "A fetish"], mode: "wild" },
  { topic: "The most revealing sext I sent was…", prompts: ["A deep fantasy", "A naughty pic", "Emotionally raw", "Accidental"], mode: "wild" },
  { topic: "I was aroused by a…", prompts: ["Scent of arousal", "Sound of passion", "Unexpected touch", "Forbidden thought"], mode: "wild" },
  { topic: "A sex tape I was part of…", prompts: ["Was thrilling", "Felt risky", "Was deleted", "Never happened"], mode: "wild" },
  { topic: "The wildest party I attended had…", prompts: ["Open hookups", "Kinky games", "Unexpected nudity", "A sexual vibe"], mode: "wild" },
  { topic: "I fantasized about someone…", prompts: ["Close to me", "Famous", "Forbidden", "In a specific act"], mode: "wild" },
  { topic: "The best foreplay I experienced was…", prompts: ["Prolonged teasing", "Kinky play", "Emotionally intense", "With toys"], mode: "wild" },
  { topic: "A sexual challenge I took was…", prompts: ["A marathon session", "A public dare", "A new kink", "A partner’s idea"], mode: "wild" },
  { topic: "I did something naughty in public…", prompts: ["Got caught", "Felt thrilling", "Was subtle", "Went all out"], mode: "wild" },
  { topic: "I used food in a sexual way…", prompts: ["As a tease", "In a kink", "During foreplay", "Messily"], mode: "wild" },
  { topic: "The quickest sex I had was…", prompts: ["Adrenaline-fueled", "In a tight spot", "Unsatisfying", "Memorable"], mode: "wild" },
  { topic: "I tried tantric sex and it…", prompts: ["Deepened connection", "Felt strange", "Was intense", "Didn’t work"], mode: "wild" },
  { topic: "A sex party I heard of or went to…", prompts: ["Sounded wild", "Was overwhelming", "Sparked curiosity", "Wasn’t for me"], mode: "wild" },
  { topic: "The sexiest outfit I wore was…", prompts: ["Barely there", "Kinky costume", "For a lover", "Made me feel bold"], mode: "wild" },
  { topic: "I got turned on by a…", prompts: ["Voice whispering", "Kinky gesture", "Fantasy scenario", "Unexpected act"], mode: "wild" },
  { topic: "A secret hookup I had…", prompts: ["Was thrilling
